use Mix.Config

config :hnmobi, :pandoc_path, "pandoc"
config :hnmobi, :kindlegen_path, "kindlegen"

config :hnmobi, Hnmobi.Scheduler,
  jobs: [
    {"* * * * *", fn -> IO.puts "Every minute i'm hustlin -- Scheduler" end},
  ]

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# HnmobiWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :hnmobo, Hnmobi.Endpoint,
  http: [port: 4000],
  url: [host: "hackernews.mobi", port: 80],
  check_origin: ["//*.hackernews.mobi"],

  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: "E9D8nsJHWzFkJ97LbLTFHk+KDVE4juwdIdKvAPMY+RR5drE/S8LQ9MvjE/jndPtw",
  server: true,
  root: "."

# Do not print debug messages in production
# config :logger, level: :info
config :logger, :console, format: "[$level] $message\n"

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :hnmobi, HnmobiWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :hnmobi, HnmobiWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :hnmobi, HnmobiWeb.Endpoint, server: true
#

# Finally import the config/prod.secret.exs
# which should be versioned separately.
# import_config "prod.secret.exs"

# https://blog.polyscribe.io/a-complete-guide-to-deploying-elixir-phoenix-applications-on-kubernetes-part-1-setting-up-d88b35b64dcd
# config :hnmobi, HnmobiWeb.Endpoint,
#  secret_key_base: "E9D8nsJHWzFkJ97LbLTFHk+KDVE4juwdIdKvAPMY+RR5drE/S8LQ9MvjE/jndPtw"

# Configure your database
config :hnmobi, Hnmobi.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "prd",
  password: "prd",
  database: "hnmobile",
  hostname: "localhost",
  pool_size: 15
